/**
 * Nautilus Common Library
 * 
 * DO NOT EDIT THIS FILE - This is part of the Nautilus template infrastructure.
 * 
 * Re-exports all common functionality for easy importing.
 */

export {
    type NautilusKeypair,
    generateKeypair,
    getPublicKeyHex,
    getAttestation,
    signIntentMessage,
    freeKeypair,
    freeCString
} from './nautilus'

export {
    nowMs,
    hexToBytes,
    bytesToHex,
    checkEndpointsStatus
} from './utils'
