// @ts-nocheck
/**
 * Nautilus FFI Library
 * 
 * DO NOT EDIT THIS FILE - This is part of the Nautilus template infrastructure.
 * 
 * This module provides TypeScript bindings to the Rust Nautilus library via FFI.
 * It handles keypair generation, attestation, and message signing.
 */

import { dlopen, FFIType } from 'bun:ffi'

/**
 * Resolves the path to the Nautilus shared library
 */
async function resolveLibPath(): Promise<string> {
    const env = process.env.NAUTILUS_LIB_PATH
    if (env && env.length > 0) return env

    const candidates = [
        './target/release/libnautilus_server.dylib',
        './target/debug/libnautilus_server.dylib',
        './target/x86_64-unknown-linux-musl/release/libnautilus_server.so',
        './target/release/libnautilus_server.so'
    ]

    for (const p of candidates) {
        try {
            if (await Bun.file(p).exists()) return p
        } catch { }
    }

    return 'libnautilus_server'
}

/**
 * Load the Nautilus FFI library
 */
const libPath = await resolveLibPath()
const lib = dlopen(libPath, {
    nautilus_generate_ed25519_keypair: { returns: FFIType.ptr, args: [] },
    nautilus_free_keypair: { returns: FFIType.void, args: [FFIType.ptr] },
    nautilus_get_public_key_hex: { returns: FFIType.cstring, args: [FFIType.ptr] },
    nautilus_get_attestation: { returns: FFIType.cstring, args: [FFIType.ptr] },
    nautilus_free_cstr: { returns: FFIType.void, args: [FFIType.cstring] },
    nautilus_sign_intent_message_json: {
        returns: FFIType.cstring,
        args: [FFIType.ptr, FFIType.ptr, FFIType.usize, FFIType.u64, FFIType.u8]
    }
})

/**
 * Nautilus Keypair - opaque pointer to Rust keypair
 */
export type NautilusKeypair = number

/**
 * Generate a new Ed25519 keypair
 */
export function generateKeypair(): NautilusKeypair {
    return lib.symbols.nautilus_generate_ed25519_keypair() as NautilusKeypair
}

/**
 * Get the public key as a hex string
 */
export function getPublicKeyHex(keypair: NautilusKeypair): string {
    const cstr = lib.symbols.nautilus_get_public_key_hex(keypair)
    // Convert FFI cstring to JavaScript string
    const result = String(cstr)
    return result
}

/**
 * Get the Nitro attestation document
 */
export function getAttestation(keypair: NautilusKeypair): string {
    const cstr = lib.symbols.nautilus_get_attestation(keypair)
    // Convert FFI cstring to JavaScript string
    const result = String(cstr)
    return result
}

/**
 * Sign an intent message and return JSON response
 * 
 * @param keypair - The keypair to sign with
 * @param payload - The payload data as a Buffer
 * @param timestampMs - Timestamp in milliseconds
 * @param intent - Intent type (default: 0)
 * @returns JSON string with signature and response
 */
export function signIntentMessage(
    keypair: NautilusKeypair,
    payload: Buffer,
    timestampMs: bigint,
    intent: number = 0
): string {
    const cstr = lib.symbols.nautilus_sign_intent_message_json(
        keypair,
        payload,
        payload.byteLength,
        timestampMs,
        intent
    )
    // Convert FFI cstring to JavaScript string
    const result = String(cstr)
    return result
}

/**
 * Free a keypair (cleanup)
 */
export function freeKeypair(keypair: NautilusKeypair): void {
    lib.symbols.nautilus_free_keypair(keypair)
}

/**
 * Free a C string (cleanup)
 */
export function freeCString(str: string): void {
    lib.symbols.nautilus_free_cstr(str)
}
