/**
 * Nautilus Utility Functions
 * 
 * DO NOT EDIT THIS FILE - This is part of the Nautilus template infrastructure.
 * 
 * Common utility functions for working with Nautilus.
 */

/**
 * Get current timestamp in milliseconds
 */
export function nowMs(): number {
    return Date.now()
}

/**
 * Convert hex string to Buffer
 * Handles both 0x-prefixed and non-prefixed hex strings
 */
export function hexToBytes(hex: string): Buffer {
    const s = hex.startsWith('0x') ? hex.slice(2) : hex
    return Buffer.from(s, 'hex')
}

/**
 * Convert Buffer to hex string with 0x prefix
 */
export function bytesToHex(bytes: Buffer): string {
    return '0x' + bytes.toString('hex')
}

/**
 * Check the status of allowed endpoints from allowed_endpoints.yaml
 * Returns a map of hostname -> reachability status
 */
export async function checkEndpointsStatus(): Promise<Record<string, boolean>> {
    try {
        const yaml = await Bun.file('allowed_endpoints.yaml').text()
        const lines = yaml.split('\n').map((l: string) => l.trim())
        const hosts = lines
            .filter((l: string) => l.startsWith('- '))
            .map((l: string) => l.slice(2))

        const result: Record<string, boolean> = {}

        for (const host of hosts) {
            const url = host.includes('.amazonaws.com')
                ? `https://${host}/ping`
                : `https://${host}`

            try {
                const ctrl = new AbortController()
                const timer = setTimeout(() => ctrl.abort(), 5000)
                const res = await fetch(url, { signal: ctrl.signal })
                clearTimeout(timer)
                result[host] = res.ok || true
            } catch {
                result[host] = false
            }
        }

        return result
    } catch {
        return {}
    }
}
